//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarkodSatışSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class kgorevler
    {
        public int Id { get; set; }
        public Nullable<bool> SatisEkran { get; set; }
        public Nullable<bool> RaporEkrani { get; set; }
        public Nullable<bool> Stok { get; set; }
        public Nullable<bool> UrunGiris { get; set; }
        public Nullable<bool> Ayarlar { get; set; }
        public Nullable<bool> FiyatGuncelleme { get; set; }
        public Nullable<bool> Yedekleme { get; set; }
    }
}
