//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarkodSatışSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public int UrunId { get; set; }
        public string Barkod { get; set; }
        public string UrunAdi { get; set; }
        public string Acıklama { get; set; }
        public string UrunGroup { get; set; }
        public Nullable<double> AlisFiyat { get; set; }
        public Nullable<double> SatisFiyat { get; set; }
        public Nullable<int> Kdvorani { get; set; }
        public Nullable<double> Kdvtutari { get; set; }
        public string Birim { get; set; }
        public Nullable<double> Miktar { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Kullanici { get; set; }
        public Nullable<bool> Onay { get; set; }
        public Nullable<double> TotalFiyat { get; set; }
    }
}
